services:
  database:
    container_name: database
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    ports:
      - 127.0.0.1:5440:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - database_network
      - migrations_network

  migrations:
    image: migrate/migrate:v4.15.1
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - migrations_network
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]

  api:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - 4000:3000
    networks:
      - api_network
      - database_network


volumes:
  database-data:


networks:
  migrations_network:
    driver: bridge
  database_network:
    driver: bridge
  api_network:
    driver: bridge